### ISSUE TITLE
ios: Failed to get 'visible' attribute of a webelement

### ISSUE THREAD

**Issue by socyrius** [appium/python-client#182]
Appium server: 1.6.5
osx: 10.12
Appium-Python-Client==0.24
selenium==3.3.1
ios: 9.3.5

After finding elements by xpath ('//XCUIElementTypeButton[contains(@name,"menu_")]'), want to check if some elements are visible or not, using get_attribute('visible'). The request failed at (webelement.py):
```
            resp = self._execute(Command.GET_ELEMENT_ATTRIBUTE, {'name': name})
            attributeValue = resp.get('value')
            if attributeValue is not None:
                if name != 'value' and attributeValue.lower() in ('true', 'false'):
                    attributeValue = attributeValue.lower()

```
with the following exception:
AttributeError: 'bool' object has no attribute 'lower'.

This works fine with the Appium Inspector (1.2.0.beta-3).

**Comment by mykola-mokhnach** [comment]
This issue has been fixed in the recent Appium beta. 1.6.5 does not contain this fix.

**Comment by socyrius** [comment]
Not sure, same issue with 1.7.0-beta.

**Comment by mykola-mokhnach** [comment]
Can you attach the server log?

**Comment by socyrius** [comment]
the server side seems to be fine:
```
[HTTP] --> GET /wd/hub/session/ddca1088-9e30-4a86-8df4-1e804d39503a/element/8F9684C1-A037-4BD8-96B5-C3C6E3DB64C9/attribute/visible {}
[MJSONWP] Driver proxy active, passing request on via HTTP proxy
[debug] [XCUITest] Executing command 'proxyReqRes'
[debug] [JSONWP Proxy] Proxying [GET /wd/hub/session/ddca1088-9e30-4a86-8df4-1e804d39503a/element/8F9684C1-A037-4BD8-96B5-C3C6E3DB64C9/attribute/visible] to [GET http://localhost:8100/session/3C8DDC63-68EF-4F40-B33D-588003B81E03/element/8F9684C1-A037-4BD8-96B5-C3C6E3DB64C9/attribute/visible] with body: {}
[debug] [JSONWP Proxy] Got response with status 200: "{\n  \"value\" : true,\n  \"sessionId\" : \"3C8DDC63-68EF-4F40-B33D-588003B81E03\",\n  \"status\" : 0\n}"
[JSONWP Proxy] Replacing sessionId 3C8DDC63-68EF-4F40-B33D-588003B81E03 with ddca1088-9e30-4a86-8df4-1e804d39503a
[HTTP] <-- GET /wd/hub/session/ddca1088-9e30-4a86-8df4-1e804d39503a/element/8F9684C1-A037-4BD8-96B5-C3C6E3DB64C9/attribute/visible 200 1059 ms - 76
``` 
(Beside the appium upgrade, I also upgraded the python selenium package to 3.5.0)

**Comment by mykola-mokhnach** [comment]
No, it's not fine. The returned value should be of type string. Can you attach the whole log, so I can see exact component versions?

**Comment by socyrius** [comment]
here is the begin of the log:

```
[Appium] Welcome to Appium v1.7.0-beta
[Appium] Appium REST http interface listener started on 0.0.0.0:4723
[HTTP] --> POST /wd/hub/session {"capabilities":{"alwaysMatch":{"platformName":"ios"},"firstMatch":[{}]},"desiredCapabilities":{"deviceName":"iPhone-6-9.3.5","appPackage":"PACKAGE-ID","wdaLocalPort":"8100","udid":"d35cf0ee1fe4621c68c349268dfbb4e1adc10190","app":"/Users/bruno/ConnectedHome/applications/4.8/chswift.ipa","noReset":true,"automationName":"XCUITest","newCommandTimeout":0,"platformVersion":"9.3.5","fullReset":false,"connectHardwareKeyboard":true,"platformName":"ios","appActivity":"ACTIVITY-ID"}}
[debug] [MJSONWP] Calling AppiumDriver.createSession() with args: [{"deviceName":"iPhone-6-9.3.5","appPackage":"PACKAGE-ID","wdaLocalPort":"8100","udid":"d35cf0ee1fe4621c68c349268dfbb4e1adc10190","app":"/Users/bruno/ConnectedHome/applications/4.8/chswift.ipa","noReset":true,"automationName":"XCUITest","newCommandTimeout":0,"platformVersion":"9.3.5","fullReset":false,"connectHardwareKeyboard":true,"platformName":"ios","appActivity":"ACTIVITY-ID"},null,{"alwaysMatch":{"platformName":"ios"},"firstMatch":[{}]}]
[debug] [BaseDriver] Event 'newSessionRequested' logged at 1504798222860 (17:30:22 GMT+0200 (CEST))
[Appium] Creating new XCUITestDriver (v2.47.1) session
[Appium] Capabilities:
[Appium]   deviceName: 'iPhone-6-9.3.5'
[Appium]   appPackage: 'PACKAGE-ID'
[Appium]   wdaLocalPort: '8100'
[Appium]   udid: 'd35cf0ee1fe4621c68c349268dfbb4e1adc10190'
[Appium]   app: '/Users/bruno/ConnectedHome/applications/4.8/chswift.ipa'
[Appium]   noReset: true
[Appium]   automationName: 'XCUITest'
[Appium]   newCommandTimeout: 0
[Appium]   platformVersion: '9.3.5'
[Appium]   fullReset: false
[Appium]   connectHardwareKeyboard: true
[Appium]   platformName: 'ios'
[Appium]   appActivity: 'ACTIVITY-ID'
[BaseDriver] Capability 'wdaLocalPort' changed from string ('8100') to integer (8100). This may cause unexpected behavior
[BaseDriver] The following capabilities were provided, but are not recognized by appium: appPackage, appActivity.
[BaseDriver] Session created with session id: 7986f5f8-8c8f-4684-9382-392a282ec5b7
[debug] [XCUITest] Xcode version set to '8.1' (tools v8.3.2.0.1.1492020469)
[debug] [XCUITest] iOS SDK Version set to '10.1'
[debug] [BaseDriver] Event 'xcodeDetailsRetrieved' logged at 1504798223093 (17:30:23 GMT+0200 (CEST))
[debug] [XCUITest] Available devices: d35cf0ee1fe4621c68c349268dfbb4e1adc10190
[debug] [XCUITest] Creating iDevice object with udid 'd35cf0ee1fe4621c68c349268dfbb4e1adc10190'
[XCUITest] Determining device to run tests on: udid: 'd35cf0ee1fe4621c68c349268dfbb4e1adc10190', real device: true
[BaseDriver] Using local app '/Users/bruno/ConnectedHome/applications/4.8/chswift.ipa'
[debug] [BaseDriver] Copying local zip to tmp dir
[debug] [BaseDriver] Unzipping /var/folders/px/21rnvk_s2b97rk2vh501vssh0000gp/T/201787-31209-kzx7yt.rfpiyn9udi/appium-app.zip
[debug] [BaseDriver] Testing zip archive: /var/folders/px/21rnvk_s2b97rk2vh501vssh0000gp/T/201787-31209-kzx7yt.rfpiyn9udi/appium-app.zip
[BaseDriver] Unzipped local app to '/var/folders/px/21rnvk_s2b97rk2vh501vssh0000gp/T/201787-31209-kzx7yt.rfpiyn9udi/Payload/chswift.app'
[debug] [BaseDriver] Event 'appConfigured' logged at 1504798225702 (17:30:25 GMT+0200 (CEST))
[debug] [XCUITest] Checking whether app '/var/folders/px/21rnvk_s2b97rk2vh501vssh0000gp/T/201787-31209-kzx7yt.rfpiyn9udi/Payload/chswift.app' is actually present on file system
[debug] [XCUITest] App is present
[debug] [iOS] Getting bundle ID from app '/var/folders/px/21rnvk_s2b97rk2vh501vssh0000gp/T/201787-31209-kzx7yt.rfpiyn9udi/Payload/chswift.app': 'com.amdocs.RichMedia.amdocs.chfd.mobile.ios.chfd'
[debug] [BaseDriver] Event 'resetStarted' logged at 1504798225730 (17:30:25 GMT+0200 (CEST))
[debug] [XCUITest] Reset: fullReset not set. Leaving as is
[debug] [BaseDriver] Event 'resetComplete' logged at 1504798225731 (17:30:25 GMT+0200 (CEST))
[debug] [iOSLog] Attempting iOS device log capture via libimobiledevice idevicesyslog
[debug] [iOSLog] Starting iOS device log capture with: 'idevicesyslog'
[debug] [BaseDriver] Event 'logCaptureStarted' logged at 1504798225830 (17:30:25 GMT+0200 (CEST))
[XCUITest] Setting up real device
[debug] [XCUITest] App 'com.amdocs.RichMedia.amdocs.chfd.mobile.ios.chfd' is already installed. No need to reinstall.
[debug] [BaseDriver] Event 'appInstalled' logged at 1504798226154 (17:30:26 GMT+0200 (CEST))
[XCUITest] Using WDA path: '/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent'
[XCUITest] Using WDA agent: '/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj'
[debug] [XCUITest] Capability 'useNewWDA' set to false, so trying to reuse currently running WDA instance at 'http://localhost:8100/'
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [XCUITest] WDA is not listening at 'http://localhost:8100/'. Rebuilding...
[debug] [BaseDriver] Event 'wdaStartAttempted' logged at 1504798226222 (17:30:26 GMT+0200 (CEST))
[XCUITest] Launching WebDriverAgent on the device
[debug] [XCUITest] Carthage found: '/usr/local/bin/carthage'
[debug] [XCUITest] Killing running processes 'xcodebuild.*d35cf0ee1fe4621c68c349268dfbb4e1adc10190, iproxy 8100' for the device d35cf0ee1fe4621c68c349268dfbb4e1adc10190...
[debug] [XCUITest] 'pgrep -nif xcodebuild.*d35cf0ee1fe4621c68c349268dfbb4e1adc10190' didn't detect any matching processes. Return code: 1
[debug] [XCUITest] 'pgrep -nif iproxy 8100' didn't detect any matching processes. Return code: 1
[debug] [XCUITest] Starting iproxy to forward traffic from local port 8100 to device port 8100 over USB
[debug] [XCUITest] Beginning test with command 'xcodebuild build-for-testing test-without-building -project /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination id=d35cf0ee1fe4621c68c349268dfbb4e1adc10190 IPHONEOS_DEPLOYMENT_TARGET=9.3' in directory '/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent'
[debug] [XCUITest] Output from xcodebuild will not be logged. To see xcode logging, use 'showXcodeLog' desired capability
[debug] [XCUITest] Waiting up to 60000ms for WebDriverAgent to start
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
...
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [XCUITest] Log file for xcodebuild test: /Users/bruno/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Logs/Test/87C4CDFF-B3C2-4D36-A9E4-B32D44DF9102/Session-WebDriverAgentRunner-2017-09-07_173040-BXi7De.log
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
...
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Got response with status 200: "{\n  \"value\" : {\n    \"state\" : \"success\",\n    \"os\" : {\n      \"name\" : \"iPhone OS\",\n      \"version\" : \"9.3.5\"\n    },\n    \"ios\" : {\n      \"simulatorVersion\" : \"9.3.5\",\n      \"ip\" : \"192.168.2.23\"\n    },\n    \"build\" : {\n      \"time\" : \"Sep  7 2017 17:30:34\"\n    }\n  },\n  \"sessionId\" : \"018B59CF-C920-4E9B-9AF3-C191E45E6396\",\n  \"status\" : 0\n}"
[debug] [XCUITest] WebDriverAgent running on ip '192.168.2.23'
[debug] [XCUITest] WebDriverAgent successfully started after 16660ms
[debug] [BaseDriver] Event 'wdaSessionAttempted' logged at 1504798247964 (17:30:47 GMT+0200 (CEST))
[debug] [XCUITest] Sending createSession command to WDA
[XCUITest] Forcing shouldUseSingletonTestManager capability value to true, because of known XCTest issues under 9.3 platform version
[debug] [JSONWP Proxy] Proxying [POST /session] to [POST http://localhost:8100/session] with body: {"desiredCapabilities":{"bundleId":"com.amdocs.RichMedia.amdocs.chfd.mobile.ios.chfd","arguments":[],"environment":{},"shouldWaitForQuiescence":true,"shouldUseTestManagerForVisibilityDetection":true,"maxTypingFrequency":60,"shouldUseSingletonTestManager":true}}
[debug] [JSONWP Proxy] Got response with status 200: {"value":{"sessionId":"0D9B7416-F123-4CF6-9547-F80F32C92DAC","capabilities":{"device":"iphone","browserName":"chfd","sdkVersion":"9.3.5","CFBundleIdentifier":"com.amdocs.RichMedia.amdocs.chfd.mobile.ios.chfd"}},"sessionId":"0D9B7416-F123-4CF6-9547-F80F32C92DAC","status":0}
[debug] [BaseDriver] Event 'wdaSessionStarted' logged at 1504798249939 (17:30:49 GMT+0200 (CEST))
[XCUITest] Setting '555' permissions to '/Users/bruno/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Logs/Test/Attachments' folder
[debug] [BaseDriver] Event 'wdaPermsAdjusted' logged at 1504798250021 (17:30:50 GMT+0200 (CEST))
[debug] [BaseDriver] Event 'wdaStarted' logged at 1504798250021 (17:30:50 GMT+0200 (CEST))
[debug] [XCUITest] Setting initial orientation to 'PORTRAIT'
[debug] [JSONWP Proxy] Proxying [POST /orientation] to [POST http://localhost:8100/session/0D9B7416-F123-4CF6-9547-F80F32C92DAC/orientation] with body: {"orientation":"PORTRAIT"}
[debug] [JSONWP Proxy] Got response with status 200: {"value":{},"sessionId":"0D9B7416-F123-4CF6-9547-F80F32C92DAC","status":0}
[debug] [BaseDriver] Event 'orientationSet' logged at 1504798251345 (17:30:51 GMT+0200 (CEST))
[Appium] New XCUITestDriver session created successfully, session 7986f5f8-8c8f-4684-9382-392a282ec5b7 added to master session list
[debug] [BaseDriver] Event 'newSessionStarted' logged at 1504798251350 (17:30:51 GMT+0200 (CEST))
[debug] [MJSONWP] Responding to client with driver.createSession() result: {"webStorageEnabled":false,"locationContextEnabled":false,"browserName":"","platform":"MAC","javascriptEnabled":true,"databaseEnabled":false,"takesScreenshot":true,"networkConnectionEnabled":false,"deviceName":"iPhone-6-9.3.5","appPackage":"PACKAGE-ID","wdaLocalPort":"8100","udid":"d35cf0ee1fe4621c68c349268dfbb4e1adc10190","app":"/Users/bruno/ConnectedHome/applications/4.8/chswift.ipa","noReset":true,"automationName":"XCUITest","newCommandTimeout":0,"platformVersion":"9.3.5","fullReset":false,"connectHardwareKeyboard":true,"platformName":"ios","appActivity":"ACTIVITY-ID"}
[HTTP] <-- POST /wd/hub/session 200 28499 ms - 650 
[HTTP] --> POST /wd/hub/session/7986f5f8-8c8f-4684-9382-392a282ec5b7/timeouts/implicit_wait {"sessionId":"7986f5f8-8c8f-4684-9382-392a282ec5b7","ms":30000}
[debug] [MJSONWP] Calling AppiumDriver.implicitWait() with args: [30000,"7986f5f8-8c8f-4684-9382-392a282ec5b7"]
[debug] [XCUITest] Executing command 'implicitWait'
[debug] [BaseDriver] Set implicit wait to 30000ms
[debug] [MJSONWP] Responding to client with driver.implicitWait() result: null
[HTTP] <-- POST /wd/hub/session/7986f5f8-8c8f-4684-9382-392a282ec5b7/timeouts/implicit_wait 200 11 ms - 76 
[HTTP] --> POST /wd/hub/session/7986f5f8-8c8f-4684-9382-392a282ec5b7/elements {"using":"accessibility id","sessionId":"7986f5f8-8c8f-4684-9382-392a282ec5b7","value":"OK"}
[debug] [MJSONWP] Calling AppiumDriver.findElements() with args: ["accessibility id","OK","7986f5f8-8c8f-4684-9382-392a282ec5b7"]
[debug] [XCUITest] Executing command 'findElements'
...
```
and the end:
```
[HTTP] --> GET /wd/hub/session/7986f5f8-8c8f-4684-9382-392a282ec5b7/element/24B0090D-8FA7-450E-9131-D0E891F9E0F3/attribute/visible {}
[MJSONWP] Driver proxy active, passing request on via HTTP proxy
[debug] [XCUITest] Executing command 'proxyReqRes'
[debug] [JSONWP Proxy] Proxying [GET /wd/hub/session/7986f5f8-8c8f-4684-9382-392a282ec5b7/element/24B0090D-8FA7-450E-9131-D0E891F9E0F3/attribute/visible] to [GET http://localhost:8100/session/0D9B7416-F123-4CF6-9547-F80F32C92DAC/element/24B0090D-8FA7-450E-9131-D0E891F9E0F3/attribute/visible] with body: {}
[debug] [JSONWP Proxy] Got response with status 200: "{\n  \"value\" : true,\n  \"sessionId\" : \"0D9B7416-F123-4CF6-9547-F80F32C92DAC\",\n  \"status\" : 0\n}"
[JSONWP Proxy] Replacing sessionId 0D9B7416-F123-4CF6-9547-F80F32C92DAC with 7986f5f8-8c8f-4684-9382-392a282ec5b7
[HTTP] <-- GET /wd/hub/session/7986f5f8-8c8f-4684-9382-392a282ec5b7/element/24B0090D-8FA7-450E-9131-D0E891F9E0F3/attribute/visible 200 1057 ms - 76 
[HTTP] --> DELETE /wd/hub/session/7986f5f8-8c8f-4684-9382-392a282ec5b7 {}
[debug] [MJSONWP] Calling AppiumDriver.deleteSession() with args: ["7986f5f8-8c8f-4684-9382-392a282ec5b7"]
[debug] [BaseDriver] Event 'quitSessionRequested' logged at 1504798402930 (17:33:22 GMT+0200 (CEST))
[Appium] Removing session 7986f5f8-8c8f-4684-9382-392a282ec5b7 from our master session list
[debug] [JSONWP Proxy] Proxying [DELETE /session/7986f5f8-8c8f-4684-9382-392a282ec5b7] to [DELETE http://localhost:8100/session/0D9B7416-F123-4CF6-9547-F80F32C92DAC] with no body
[debug] [JSONWP Proxy] Got response with status 200: "{\n  \"value\" : {\n\n  },\n  \"sessionId\" : \"6DD2006F-EE51-4FD7-BA3C-6197FAF7990A\",\n  \"status\" : 0\n}"
[XCUITest] Setting '755' permissions to '/Users/bruno/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Logs/Test/Attachments' folder
[debug] [XCUITest] Not clearing log files. Use `clearSystemFiles` capability to turn on.
[debug] [iOSLog] Stopping iOS log capture
[debug] [BaseDriver] Event 'quitSessionFinished' logged at 1504798403376 (17:33:23 GMT+0200 (CEST))
[debug] [MJSONWP] Received response: null
[debug] [MJSONWP] But deleting session, so not returning
[debug] [MJSONWP] Responding to client with driver.deleteSession() result: null
[HTTP] <-- DELETE /wd/hub/session/7986f5f8-8c8f-4684-9382-392a282ec5b7 200 449 ms - 76 

```

$ npm list -g | grep appium
```
├─┬ appium@1.7.0-beta
│ ├─┬ appium-android-driver@1.26.0
│ │ ├─┬ appium-adb@2.28.0
│ │ ├─┬ appium-android-bootstrap@2.9.3
│ │ │ ├─┬ appium-uiautomator@1.1.2
│ │ ├── appium-android-ime@2.0.0
│ │ ├─┬ appium-chromedriver@2.12.4
│ │ ├── appium-unlock@0.1.1
│ │ ├── io.appium.settings@2.2.1
│ ├─┬ appium-base-driver@2.15.2
│ ├─┬ appium-espresso-driver@1.0.0-beta.3
│ ├─┬ appium-fake-driver@0.2.0
│ ├─┬ appium-ios-driver@1.27.0
│ │ ├─┬ appium-ios-simulator@2.2.5
│ │ ├─┬ appium-remote-debugger@3.6.0
│ │ ├─┬ appium-xcode@3.3.1
│ ├─┬ appium-mac-driver@1.0.2
│ ├─┬ appium-selendroid-driver@1.6.2
│ ├─┬ appium-support@2.8.3
│ ├─┬ appium-uiautomator2-driver@0.6.1
│ │ ├── appium-uiautomator2-server@0.1.8
│ ├─┬ appium-windows-driver@0.5.0
│ ├─┬ appium-xcuitest-driver@2.47.1
│ ├── appium-youiengine-driver@1.0.13
├─┬ appium-xcuitest-driver@2.28.1
│ ├─┬ appium-base-driver@2.7.2
│ ├─┬ appium-ios-driver@1.21.2
│ │ ├─┬ appium-instruments@3.9.3
│ │ ├─┬ appium-remote-debugger@3.3.0
│ ├─┬ appium-ios-simulator@1.23.2
│ ├─┬ appium-support@2.8.0
│ ├─┬ appium-xcode@3.2.2
```

**Comment by jlipps** [comment]
@mykola-mokhnach does appium-xcuitest-driver 2.47.1 have a WDA version with your fixes?

**Comment by mykola-mokhnach** [comment]
@socyrius is the command executed in native or web context?

**Comment by jlipps** [comment]
@mykola-mokhnach the fix to return a string rather than a boolean I guess? I thought you were saying this was a fix which already existed.

**Comment by mykola-mokhnach** [comment]
yes the fix exists in the given driver version. That is why I'm surprised that it does not work

**Comment by mykola-mokhnach** [comment]
I have no glue why the fixed code does not work there %)
@socyrius As a workaround you can add a very simple change into python driver:

replace `attributeValue = resp.get('value')` with `attributeValue = unicode(resp.get('value'))`

**Comment by socyrius** [comment]
ok, thanks. the script is executed in a native context. is there a test I can do to help investigation ?

**Comment by mykola-mokhnach** [comment]
I have one idea about what the problem can be. can you please add `['GET', /attribute/],` item to the NO_PROXY_NATIVE_LIST array inside /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/lib/driver.js and then execute `gulp trinspile` inside this folder (npm will, probably, ask you to install additional modules). After the transpiration is successful restart your server and try again

**Comment by socyrius** [comment]
done. it works fine (previous unicode workaround in webelement.py removed), the `get_attribute('visible')` request returns `u'true'` or `u'false'`

**Comment by mykola-mokhnach** [comment]
Thanks. I'll create a PR
